### ISSUE TITLE
Image simulations of galaxies with high-resolution SEDs

### ISSUE THREAD

**Issue by sidneymau** [LSSTDESC/SprintWeek2023#16]
# Image simulations of galaxies with high-resolution SEDs

Use catalogs from [lsstdesc-diffsky](https://lsstdesc-diffsky.readthedocs.io/en/latest/) and [DSPS](https://dsps.readthedocs.io/en/latest/index.html) to build image simulations featuring galaxies with high-resolution spectral energy distributions.

Contacts: @sidneymau 
Day/Time: TBD
Main communication channel: #desc-wl-shear-color
GitHub repo: TBD (maybe https://github.com/LSSTDESC/chromatic-shear-bias)
Zoom room (if applicable): TBD

## Goals and deliverable

Goals:
- Learn how to use the `lsstdesc-diffsky` catalogs, including `DSPS` to build high resolution SEDs for appropriate galaxy catalogs
- Create GalSim objects with these SEDs and other galaxy params
- Draw images using GalSim of these objects

Deliverable:
- Multiband image simulations of galaxies with high-resolution SEDs (e.g., _g_, _r_, _i_, images of a scene of simple exponential galaxies with high-resolution SEDs placed on a grid)

## Resources and skills needed

- NERSC access
- GalSim

## Detailed description

If the above is completed early, then I will propose a stretch goal of running a small campaign of image simulations and running metadetect to measure the multiplicative bias.

**Comment by torluca** [comment]
Hi Sidney, I worked with Andrew Hearin and the PZ group in creating an interface in RAIL to generate SEDs with DSPS. I might be of help

**Comment by sidneymau** [comment]
I have integrated the dsps SEDs with GalSim, after which I discovered a bug (cf. https://github.com/GalSim-developers/GalSim/pull/1256). This sprint is more or less complete!
![image](https://github.com/LSSTDESC/SprintWeek2023/assets/26752606/27da6156-daeb-4865-a17a-a1bc001f1c95)
